name: Kika FUTBIN Price Update

on:
  workflow_dispatch:

  repository_dispatch:
    types:
      - kika-price-update

jobs:
  update-price:

    runs-on: ubuntu-latest

    steps:

      - name: Repository auschecken
        uses: actions/checkout@v4

      - name: Python installieren
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Abhängigkeiten installieren
        run: |
          pip install discord.py aiohttp

      - name: Kika Preis aktualisieren
        env:
          DISCORD_TOKEN: ${{ secrets.DISCORD_TOKEN }}
          CHANNEL_ID: ${{ secrets.CHANNEL_ID }}
          PARSE_API_KEY: ${{ secrets.PARSE_API_KEY }}
        run: |
          python futbin_price_embed_5min_fixed.py
